"""BIS sources: expand to 9 (Raid + M+ + Overall for each website)

Revision ID: 0069
Revises: 0068
Create Date: 2026-04-04

Adds the 4 missing bis_list_sources rows so every website offers all three
content types (Raid Only, M+ Only, Overall).  Also clears the existing
bis_scrape_targets and bis_scrape_log rows generated by the broken
discover_targets logic (wrong content_type per source) so the admin can
re-run Discover URLs cleanly.
"""

from alembic import op

revision = "0069"
down_revision = "0068"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Add the 4 missing sources
    op.execute(
        """
        INSERT INTO guild_identity.bis_list_sources
            (name, short_label, origin, content_type, is_default, is_active, sort_order)
        VALUES
            ('Archon Overall',    'Archon',  'archon',    'overall',     FALSE, TRUE,  25),
            ('Wowhead Raid',      'WH Raid', 'wowhead',   'raid',        FALSE, TRUE,  28),
            ('Wowhead M+',        'WH M+',   'wowhead',   'mythic_plus', FALSE, TRUE,  29),
            ('Icy Veins Overall', 'IV',      'icy_veins', 'overall',     FALSE, TRUE,  55)
        ON CONFLICT (name) DO NOTHING
        """
    )

    # Clear stale targets and log generated by the old broken discover logic
    # (each source was creating targets for all content_types of its origin,
    # not just its own content_type).  The admin will re-run Discover URLs.
    op.execute("DELETE FROM guild_identity.bis_scrape_log")
    op.execute("DELETE FROM guild_identity.bis_scrape_targets")


def downgrade() -> None:
    op.execute(
        """
        DELETE FROM guild_identity.bis_list_sources
         WHERE name IN (
             'Archon Overall', 'Wowhead Raid', 'Wowhead M+', 'Icy Veins Overall'
         )
        """
    )
